import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const api = (url, options = {}) => fetch(url, {
  ...options,
  headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}) }
}).then(async response => {
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || 'Request failed');
  return body;
});

function parseCommand(text) {
  const lower = text.toLowerCase();
  const steps = [];
  if (/schedule|calendar|meeting|event/.test(lower)) {
    const title = text.match(/(?:schedule|create)(?: a| an)?\s+(.+?)(?:\s+(?:tomorrow|today|on)\b|$)/i)?.[1] || '';
    steps.push({ type: 'calendar', label: 'Create calendar event', title, raw: text });
  }
  if (/remind|reminder/.test(lower)) steps.push({ type: 'reminder', label: 'Create personal reminder', text: text.replace(/.*?remind(?: me)?(?: to)?/i, '').trim(), when: text.match(/(?:at|on)\s+(.+)$/i)?.[1] || 'unscheduled' });
  if (/telegram|send (?:a )?message|message/.test(lower)) steps.push({ type: 'telegram', label: 'Send Telegram message', recipient: text.match(/(?:to|send)\s+([A-Z][a-z]+)/)?.[1] || '', message: text.match(/(?:saying|that)\s+(.+)/i)?.[1] || '' });
  if (/upload|drive|document|file/.test(lower) && /upload|find|search/.test(lower)) { const upload = lower.includes('upload'); steps.push({ type: upload ? 'drive-upload' : 'drive-search', label: upload ? 'Upload to Stark Archive' : 'Search Stark Archive', query: text }); }
  return steps.length ? steps : [{ type: 'info', label: 'Interpret request', raw: text }];
}

function App() {
  const [messages, setMessages] = useState([{ role: 'jarvis', text: 'Good evening, Tony. All local systems are online. What shall we handle?' }]);
  const [input, setInput] = useState(''); const [queue, setQueue] = useState([]); const [running, setRunning] = useState(false); const [status, setStatus] = useState(null); const [preview, setPreview] = useState({ reminders: [], history: [], calendar: [], drive: [] }); const [tab, setTab] = useState('reminders'); const [confirmation, setConfirmation] = useState(null); const [file, setFile] = useState(null);
  const refresh = () => api('/api/preview').then(setPreview).catch(() => {}); const say = text => setMessages(current => [...current, { role: 'jarvis', text }]);
  useEffect(() => { api('/api/status').then(setStatus).catch(error => say(error.message)); refresh(); }, []);
  async function runStep(step) { setQueue(items => items.map(item => item === step ? { ...item, state: 'RUNNING' } : item)); try { if (step.type === 'reminder') { await api('/api/reminders', { method: 'POST', body: JSON.stringify({ text: step.text || step.raw, when: step.when }) }); say(`Reminder created: ${step.text || step.raw}`); setTab('reminders'); } else if (step.type === 'calendar') { if (!step.title) { say('I need the meeting title before I can schedule it.'); return; } await api('/api/calendar/events', { method: 'POST', body: JSON.stringify({ summary: step.title, description: step.raw }) }); say('Calendar event created and the live preview was refreshed.'); setTab('calendar'); } else if (step.type === 'telegram') { await api('/api/telegram/send', { method: 'POST', body: JSON.stringify({ recipient: step.recipient, message: step.message }) }); say(`Telegram delivered to ${step.recipient}.`); setTab('communication'); } else if (step.type === 'drive-search') { const data = await api(`/api/drive/search?q=${encodeURIComponent(step.query)}`); setPreview(current => ({ ...current, drive: data.files || [] })); say(`I found ${(data.files || []).length} Drive files.`); setTab('drive'); } else if (step.type === 'drive-upload') { say('Select a document in the Stark Archive panel, then upload it.'); setTab('drive'); } else say('I understood the request, but no external action was selected.'); } catch (error) { say(`Action not completed: ${error.message}`); } finally { setQueue(items => items.map(item => item === step ? { ...item, state: 'DONE' } : item)); refresh(); } }
  async function process(steps) { setRunning(true); for (const step of steps) await runStep(step); setRunning(false); }
  async function submit(event) { event.preventDefault(); const text = input.trim(); if (!text) return; setMessages(current => [...current, { role: 'user', text }]); setInput(''); let steps; try { const ai = await api('/api/ai/interpret', { method: 'POST', body: JSON.stringify({ command: text }) }); if (ai.configured && Array.isArray(ai.steps)) { steps = ai.steps; if (ai.reply) say(ai.reply); } } catch (error) { say('Mistral is not reachable right now; I switched to the local command parser. Start the Express server with npm run dev.'); } steps = steps || parseCommand(text); setQueue(current => [...current, ...steps.map(step => ({ ...step, state: 'WAITING' }))]); if (steps.some(step => ['calendar', 'telegram'].includes(step.type))) setConfirmation({ text, steps }); else process(steps); }
  async function upload() { if (!file) return; say(`Preparing ${file.name} for the Stark Archive…`); const form = new FormData(); form.append('file', file); try { await api('/api/drive/upload', { method: 'POST', body: form }); say('Document uploaded to Drive.'); } catch (error) { say(`Upload not completed: ${error.message}`); } }
  const previewContent = tab === 'reminders' ? <Preview title="PERSONAL REMINDERS" items={preview.reminders} empty="No reminders yet. Try “Remind me to check the reactor at 8 PM.”"/> : tab === 'calendar' ? <Preview title="GOOGLE CALENDAR" items={preview.calendar} empty={status?.integrations.calendar.configured ? 'No upcoming events loaded.' : 'Google Calendar is not configured. Add a server access token to enable live events.'}/> : tab === 'communication' ? <Preview title="RECENT COMMUNICATIONS" items={preview.history} empty="No JARVIS communications yet."/> : <div className="preview-body"><div className="preview-title">STARK ARCHIVE</div><div className="upload"><input type="file" onChange={event => setFile(event.target.files[0])}/><button onClick={upload} disabled={!file}>UPLOAD</button></div>{preview.drive.length ? preview.drive.map(fileItem => <div className="row" key={fileItem.id}><span>{fileItem.name}<small>{fileItem.mimeType} · {fileItem.modifiedTime}</small></span><a href={fileItem.webViewLink} target="_blank">OPEN</a></div>) : <p className="muted">Drive search and upload require server-side Google credentials.</p>}</div>;
  return <main className="app"><header><div><div className="eyebrow">STARK INDUSTRIES / SECURE NODE 07</div><h1>JARVIS <span>COMMAND CENTRE</span></h1></div><div className="online"><i/> {status?.assistant || 'CONNECTING'}</div></header><section className="layout"><div className="assistant panel"><div className="panel-head"><b>ASSISTANT CHANNEL</b><span>QUEUE {queue.filter(item => item.state !== 'DONE').length}</span></div><div className="chat">{messages.map((message, index) => <div className={`message ${message.role}`} key={index}><small>{message.role === 'user' ? 'TONY' : 'JARVIS'}</small><p>{message.text}</p></div>)}</div><form onSubmit={submit}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Tell JARVIS what to do…"/><button>EXECUTE</button></form></div><aside className="side"><div className="panel queue"><div className="panel-head"><b>COMMAND QUEUE</b><span>{running ? 'PROCESSING' : 'READY'}</span></div>{queue.length ? <ol>{queue.map((item, index) => <li key={index}><span>{item.label}</span><em>{item.state}</em></li>)}</ol> : <p className="muted">No pending operations.</p>}</div><div className="panel integrations"><div className="panel-head"><b>INTEGRATIONS</b></div>{status && Object.entries(status.integrations).map(([name, value]) => <div className="integration" key={name}><span>{name.toUpperCase()}</span><em className={value.configured ? 'ok' : ''}>{value.label}</em></div>)}</div></aside></section><section className="preview panel"><div className="tabs">{['reminders', 'calendar', 'drive', 'communication'].map(name => <button className={tab === name ? 'active' : ''} onClick={() => setTab(name)} key={name}>{name.toUpperCase()}</button>)}</div>{previewContent}</section>{confirmation && <div className="confirm"><div className="confirm-card"><div className="eyebrow">ACTION CONFIRMATION</div><h2>Execute this plan?</h2><p>{confirmation.text}</p><ol>{confirmation.steps.map((step, index) => <li key={index}>{step.label}</li>)}</ol><button onClick={() => { const steps = confirmation.steps; setConfirmation(null); process(steps); }}>CONFIRM</button><button className="quiet" onClick={() => setConfirmation(null)}>CANCEL</button></div></div>}</main>;
}

function Preview({ title, items, empty }) { return <div className="preview-body"><div className="preview-title">{title}</div>{items.length ? items.map((item, index) => <div className="row" key={item.id || index}><span>{item.text || item.summary || item.recipient}<small>{item.when || item.start?.dateTime || item.message || ''}</small></span><b>{item.status || 'ACTIVE'}</b></div>) : <p className="muted">{empty}</p>}</div>; }
createRoot(document.getElementById('root')).render(<App/>);
