import express from 'express';import cors from 'cors';import dotenv from 'dotenv';import multer from 'multer';import fs from 'node:fs';import path from 'node:path';
dotenv.config();const app=express(),upload=multer({storage:multer.memoryStorage()});const PORT=process.env.PORT||8787;const dataFile=path.join(process.cwd(),'server','data.json');
function readData(){try{return JSON.parse(fs.readFileSync(dataFile,'utf8'))}catch{return {reminders:[],history:[]}}}function writeData(d){fs.mkdirSync(path.dirname(dataFile),{recursive:true});fs.writeFileSync(dataFile,JSON.stringify(d,null,2))}function contacts(){try{return JSON.parse(process.env.TELEGRAM_CONTACTS_JSON||'{}')}catch{return {}}}function createReminder(text,when){const d=readData();const item={id:Date.now(),text,when:when||'unscheduled',createdAt:new Date().toISOString(),done:false};d.reminders.unshift(item);writeData(d);return item}
app.use(cors());app.use(express.json());
app.get('/api/status',(req,res)=>res.json({assistant:'ONLINE',integrations:{mistral:{configured:Boolean(process.env.MISTRAL_API_KEY),label:process.env.MISTRAL_API_KEY?'READY':'LOCAL PARSER'},calendar:{configured:Boolean(process.env.GOOGLE_ACCESS_TOKEN),label:process.env.GOOGLE_ACCESS_TOKEN?'CONNECTED':'NOT CONFIGURED'},drive:{configured:Boolean(process.env.GOOGLE_ACCESS_TOKEN),label:process.env.GOOGLE_ACCESS_TOKEN?'CONNECTED':'NOT CONFIGURED'},telegram:{configured:Boolean(process.env.TELEGRAM_BOT_TOKEN),label:process.env.TELEGRAM_BOT_TOKEN?'READY':'NOT CONFIGURED'},reminders:{configured:true,label:'ACTIVE'}}}));
app.post('/api/ai/interpret',async(req,res)=>{if(!process.env.MISTRAL_API_KEY)return res.json({configured:false});const command=String(req.body.command||'');const system=`You are JARVIS command parser. Return ONLY valid JSON: {"reply":"short response","steps":[{"type":"reminder|calendar|telegram|drive-search|drive-upload|info","label":"human label","text":"reminder text if relevant","when":"time/date if relevant","title":"event title if relevant","recipient":"Telegram contact if relevant","message":"message if relevant","query":"search text if relevant"}]}. Split multi-action commands into ordered steps. Never claim an action happened. If a required field is missing, return one info step and explain it in reply.`;try{const r=await fetch('https://api.mistral.ai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.MISTRAL_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.MISTRAL_MODEL||'mistral-small-latest',temperature:0.1,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:command}]})});const j=await r.json();if(!r.ok)return res.status(502).json({error:j.message||'Mistral request failed.'});const content=j.choices?.[0]?.message?.content||'{}';const parsed=JSON.parse(content.replace(/^```json\s*|\s*```$/g,''));res.json({configured:true,...parsed});}catch(e){res.status(502).json({error:`Mistral interpretation unavailable: ${e.message}`})}});
app.get('/api/preview',(req,res)=>{const d=readData();res.json({reminders:d.reminders,history:d.history,calendar:[],drive:[]})});
app.post('/api/reminders',(req,res)=>{const {text,when}=req.body;if(!text)return res.status(400).json({error:'Reminder text is required.'});res.json(createReminder(text,when))});
app.delete('/api/reminders/:id',(req,res)=>{const d=readData();d.reminders=d.reminders.filter(x=>String(x.id)!==req.params.id);writeData(d);res.sendStatus(204)});
app.post('/api/calendar/events',async(req,res)=>{if(!process.env.GOOGLE_ACCESS_TOKEN)return res.status(503).json({error:'Google Calendar is not configured. Add GOOGLE_ACCESS_TOKEN on the server.'});try{const r=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{Authorization:`Bearer ${process.env.GOOGLE_ACCESS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify(req.body)});const json=await r.json();if(!r.ok)return res.status(r.status).json({error:json.error?.message||'Calendar request failed.'});res.json(json)}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/calendar/events',async(req,res)=>{if(!process.env.GOOGLE_ACCESS_TOKEN)return res.json({configured:false,events:[]});try{const r=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=10',{headers:{Authorization:`Bearer ${process.env.GOOGLE_ACCESS_TOKEN}`}});const j=await r.json();res.status(r.ok?200:r.status).json({configured:true,events:j.items||[],error:j.error?.message})}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/drive/search',async(req,res)=>{if(!process.env.GOOGLE_ACCESS_TOKEN)return res.status(503).json({error:'Google Drive is not configured. Add GOOGLE_ACCESS_TOKEN on the server.'});const q=encodeURIComponent(`name contains '${String(req.query.q||'').replaceAll("'","\\'")}' and trashed = false`);try{const r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${q}&fields=files(id,name,mimeType,modifiedTime,webViewLink)`,{headers:{Authorization:`Bearer ${process.env.GOOGLE_ACCESS_TOKEN}`}});const j=await r.json();res.status(r.ok?200:r.status).json(j)}catch(e){res.status(502).json({error:e.message})}});
app.post('/api/drive/upload',upload.single('file'),async(req,res)=>{if(!process.env.GOOGLE_ACCESS_TOKEN)return res.status(503).json({error:'Google Drive is not configured. The selected file was not uploaded.'});res.status(501).json({error:'Drive multipart upload is scaffolded; configure the Google OAuth upload adapter before use.'})});
app.post('/api/telegram/send',async(req,res)=>{const {recipient,message}=req.body;const chatId=contacts()[recipient];if(!recipient||!message)return res.status(400).json({error:'Recipient and message are required.'});if(!process.env.TELEGRAM_BOT_TOKEN||!chatId)return res.status(503).json({error:`Telegram recipient ${recipient} is not configured on the server.`});try{const r=await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text:message})});const j=await r.json();if(!r.ok||!j.ok)return res.status(502).json({error:j.description||'Telegram delivery failed.'});const d=readData();d.history.unshift({recipient,message,time:new Date().toISOString(),status:'SENT'});writeData(d);res.json(j.result)}catch(e){res.status(502).json({error:e.message})}});
app.post('/api/command',async(req,res)=>{const {intent,text,when}=req.body;if(intent==='reminder'){if(!text)return res.status(400).json({error:'Reminder text is required.'});return res.json(createReminder(text,when))}res.json({ok:true})});
app.listen(PORT,()=>console.log(`JARVIS server listening on http://localhost:${PORT}`));
